AventraInterviewTask/Controllers/EventActionListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AventraInterviewTask.Models;
using AventraInterviewTask.Models.ViewModels;

namespace AventraInterviewTask.Controllers
{
    public class EventActionListsController : Controller
    {
        private readonly EventContext _context;

        public EventActionListsController(EventContext context)
        {
            _context = context;
        }

        // GET: EventActionLists
        public async Task<IActionResult> Index()
        {
            var eventContext = await _context.EventActionItem.Include(e => e.EventCategory).ToListAsync();
            return View(eventContext);
        }

        

        // GET: EventActionLists/Create
        public async Task<IActionResult> Create()
        {
            EventActionViewModel model = new EventActionViewModel()
            {
                EventCategoryList = await _context.EventCategory.ToListAsync(),
                EventActionItem = new Models.EventActionItem(),
                
                EventActionItemList = await _context.EventActionItem
                                            .OrderBy(p=>p.EventActionType)
                                            .Select(p=>p.EventActionType)
                                            .Distinct().ToListAsync()
                
            };
            //ViewData["EventCategoryId"] = new SelectList(_context.EventCategory, "Id", "EventType");
            return View(model);
        }



        // GET: EventActionLists/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EventActionViewModel model)
        {
            if (ModelState.IsValid)
            {
                var doesActionExist = _context.EventActionItem
                    .Include(s => s.EventCategory)
                    .Where(s => s.EventActionType == model.EventActionItem.EventActionType && s.EventCategory.Id == model.EventActionItem.EventCategoryId);

                if (doesActionExist.Count() > 0) {
                    //error
                }
                else
                {
                    _context.EventActionItem.Add(model.EventActionItem);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
               
            return View(model);
        }


        [ActionName("GetEventActionItem")]
        public async Task<IActionResult> GetEventActionItem(int id)
        {
            List<EventActionItem> Items = new List<EventActionItem>();
            Items = await (from Item in _context.EventActionItem 
                                where Item.EventCategoryId == id 
                                select Item).ToListAsync();
            return Json(new SelectList(Items, "Id", "EventActionType"));
        }

       
    }
}

AventraInterviewTask/Controllers/EventActionPropertiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AventraInterviewTask.Models;
using AventraInterviewTask.Models.ViewModels;
using System.Xml.Serialization;
using System.Xml;
using System.IO;
using Microsoft.AspNetCore.Http;
using System.Data;

namespace AventraInterviewTask.Controllers
{
    public class EventActionPropertiesController : Controller
    {
        private readonly EventContext _context;

        public EventActionPropertiesController(EventContext context)
        {
            _context = context;
        }

        // GET: EventActionProperties
        public async Task<IActionResult> Index()
        {
            var eventContext = _context.EventActionProperty.Include(e => e.EventActionItem).Include(e => e.EventCategory);
            return View(await eventContext.ToListAsync());
        }



        // GET: EventActionProperties/Create
       public async Task<IActionResult> Create()
        {
            EventActionPropertyViewModel model = new EventActionPropertyViewModel()
            {
                EventCategoryList = await _context.EventCategory.ToListAsync(),
                EventActionItemList = await _context.EventActionItem.ToListAsync(),
                EventActionProperty=new Models.EventActionProperty()

            };
            return View(model);
        }

        // POST: EventActionProperties/Create
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EventActionPropertyViewModel model)
        {
            if (ModelState.IsValid)
            {
                var data=model.EventActionProperty;
                data.EventActionType = await (from item in _context.EventActionItem where item.Id == data.EventActionItemId select item.EventActionType).FirstOrDefaultAsync();
                data.EventType = await (from item in _context.EventCategory where item.Id == data.EventCategoryId select item.EventType).FirstOrDefaultAsync();


                XmlSerializer xsSubmit = new XmlSerializer(data.GetType());

                var filename = model.EventActionProperty.Username + ".xml";
                using (var sww = new FileStream(@"d:\"+ filename, FileMode.Create))
                {
                    xsSubmit.Serialize(sww, data);   
                }

                _context.EventActionProperty.Add(model.EventActionProperty);
                await _context.SaveChangesAsync();
               return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        
    }}

AventraInterviewTask/Controllers/EventCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AventraInterviewTask.Models;

namespace AventraInterviewTask.Controllers
{
    public class EventCategoriesController : Controller
    {
        private readonly EventContext _context;

        public EventCategoriesController(EventContext context)
        {
            _context = context;
        }

        // GET: EventCategories
        public async Task<IActionResult> Index()
        {
            return View(await _context.EventCategory.ToListAsync());
        }

        
        // GET: EventCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: EventCategories/Create
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,EventType,EventName")] EventCategory eventCategory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventCategory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(eventCategory);
        }
       

        
    }
}

AventraInterviewTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AventraInterviewTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="EventActionProperties" asp-action="Create">Aventra</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenulink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropDownMenulink">
                                <a class="dropdown-item" asp-action="Index" asp-controller="EventCategories" >EventCategory</a>
                                <a class="dropdown-item" asp-action="Index" asp-controller="EventActionLists" >EventActionList</a>   
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="dropdown-item" asp-action="Create" asp-controller="EventActionProperties">Create-Xml-Form</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AventraInterviewTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>